//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoTrans.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PhoneticsPanelVisibleStore {
            get {
                return ((bool)(this["PhoneticsPanelVisibleStore"]));
            }
            set {
                this["PhoneticsPanelVisibleStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1,-1")]
        public global::System.Windows.Point WindowsPositionStore {
            get {
                return ((global::System.Windows.Point)(this["WindowsPositionStore"]));
            }
            set {
                this["WindowsPositionStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800,600")]
        public global::System.Windows.Size WindowSizeStore {
            get {
                return ((global::System.Windows.Size)(this["WindowSizeStore"]));
            }
            set {
                this["WindowSizeStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState WindowStateStore {
            get {
                return ((global::System.Windows.WindowState)(this["WindowStateStore"]));
            }
            set {
                this["WindowStateStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OutputDeviceIndexStore {
            get {
                return ((int)(this["OutputDeviceIndexStore"]));
            }
            set {
                this["OutputDeviceIndexStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double SlowedPlaybackSpeedStore {
            get {
                return ((double)(this["SlowedPlaybackSpeedStore"]));
            }
            set {
                this["SlowedPlaybackSpeedStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:01")]
        public global::System.TimeSpan WaveformSmallJumpStore {
            get {
                return ((global::System.TimeSpan)(this["WaveformSmallJumpStore"]));
            }
            set {
                this["WaveformSmallJumpStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public double SetupTextFontSizeStore {
            get {
                return ((double)(this["SetupTextFontSizeStore"]));
            }
            set {
                this["SetupTextFontSizeStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpeakersDatabasePathStore {
            get {
                return ((string)(this["SpeakersDatabasePathStore"]));
            }
            set {
                this["SpeakersDatabasePathStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveWholeSpeakerStore {
            get {
                return ((bool)(this["SaveWholeSpeakerStore"]));
            }
            set {
                this["SaveWholeSpeakerStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSpeakerImageStore {
            get {
                return ((bool)(this["ShowSpeakerImageStore"]));
            }
            set {
                this["ShowSpeakerImageStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double MaxSpeakerImageWidthStore {
            get {
                return ((double)(this["MaxSpeakerImageWidthStore"]));
            }
            set {
                this["MaxSpeakerImageWidthStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCustomParamsStore {
            get {
                return ((bool)(this["ShowCustomParamsStore"]));
            }
            set {
                this["ShowCustomParamsStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double VideoPanelWidthStore {
            get {
                return ((double)(this["VideoPanelWidthStore"]));
            }
            set {
                this["VideoPanelWidthStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("----")]
        public string LocaleStore {
            get {
                return ((string)(this["LocaleStore"]));
            }
            set {
                this["LocaleStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AliceBlue")]
        public string ParagraphBackgroundStore {
            get {
                return ((string)(this["ParagraphBackgroundStore"]));
            }
            set {
                this["ParagraphBackgroundStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public string SectionBackgroundStore {
            get {
                return ((string)(this["SectionBackgroundStore"]));
            }
            set {
                this["SectionBackgroundStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightPink")]
        public string ChapterBackgroundStore {
            get {
                return ((string)(this["ChapterBackgroundStore"]));
            }
            set {
                this["ChapterBackgroundStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AntiqueWhite")]
        public string ActiveParagraphBackgroundStore {
            get {
                return ((string)(this["ActiveParagraphBackgroundStore"]));
            }
            set {
                this["ActiveParagraphBackgroundStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AliceBlue")]
        public string PhoneticParagraphBackgroundStore {
            get {
                return ((string)(this["PhoneticParagraphBackgroundStore"]));
            }
            set {
                this["PhoneticParagraphBackgroundStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public string PhoneticParagraphDisabledBackgroundStore {
            get {
                return ((string)(this["PhoneticParagraphDisabledBackgroundStore"]));
            }
            set {
                this["PhoneticParagraphDisabledBackgroundStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AntiqueWhite")]
        public string WaveformBackgroundStore {
            get {
                return ((string)(this["WaveformBackgroundStore"]));
            }
            set {
                this["WaveformBackgroundStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string WaveformForegroundStore {
            get {
                return ((string)(this["WaveformForegroundStore"]));
            }
            set {
                this["WaveformForegroundStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public string WaveformTimelineBackgroundStore {
            get {
                return ((string)(this["WaveformTimelineBackgroundStore"]));
            }
            set {
                this["WaveformTimelineBackgroundStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightPink")]
        public string WaveformSpeakerBackgroundStore {
            get {
                return ((string)(this["WaveformSpeakerBackgroundStore"]));
            }
            set {
                this["WaveformSpeakerBackgroundStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public string ParagraphBeginColorStore {
            get {
                return ((string)(this["ParagraphBeginColorStore"]));
            }
            set {
                this["ParagraphBeginColorStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string ParagraphEndColorStore {
            get {
                return ((string)(this["ParagraphEndColorStore"]));
            }
            set {
                this["ParagraphEndColorStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public string WaveformBlockMarkColorStore {
            get {
                return ((string)(this["WaveformBlockMarkColorStore"]));
            }
            set {
                this["WaveformBlockMarkColorStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoPanelVisibleStore {
            get {
                return ((bool)(this["VideoPanelVisibleStore"]));
            }
            set {
                this["VideoPanelVisibleStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalSpeakerAtributeCategories {
            get {
                return ((string)(this["AdditionalSpeakerAtributeCategories"]));
            }
            set {
                this["AdditionalSpeakerAtributeCategories"] = value;
            }
        }
    }
}
