//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoTrans.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanoTrans.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programu.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapitola 0.
        /// </summary>
        public static string DefaultChapterText {
            get {
                return ResourceManager.GetString("DefaultChapterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekce 0.
        /// </summary>
        public static string DefaultSectionText {
            get {
                return ResourceManager.GetString("DefaultSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stahování.
        /// </summary>
        public static string DownloadFileWindowTitle {
            get {
                return ResourceManager.GetString("DownloadFileWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastala neočekávaná chyba programu. Abyste zabránily ztrátě dat uložte změny a restartujte NanoTrans.
        /// </summary>
        public static string ExceptionWindowBigMessage {
            get {
                return ResourceManager.GetString("ExceptionWindowBigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpis chyby:.
        /// </summary>
        public static string ExceptionWindowExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionWindowExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit a restartovat.
        /// </summary>
        public static string ExceptionWindowSaveAndRestartButton {
            get {
                return ResourceManager.GetString("ExceptionWindowSaveAndRestartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastala neočekáváná výjimka.
        /// </summary>
        public static string ExceptionWindowTitle {
            get {
                return ResourceManager.GetString("ExceptionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory obrázků|*.jpg;*.jpeg;*.png;*.gif;*.bmp|Všechny soubory (*.*)|*.*.
        /// </summary>
        public static string FileDialogLoadImageFilter {
            get {
                return ResourceManager.GetString("FileDialogLoadImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít soubor s obrázkem mluvčího....
        /// </summary>
        public static string FileDialogLoadImageTitle {
            get {
                return ResourceManager.GetString("FileDialogLoadImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory všech importovatelných typů({0})|{0}.
        /// </summary>
        public static string FileDialogLoadImportFilter {
            get {
                return ResourceManager.GetString("FileDialogLoadImportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importovat soubor.
        /// </summary>
        public static string FileDialogLoadImportTitle {
            get {
                return ResourceManager.GetString("FileDialogLoadImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozšíření OpenOffice 3 {*.zip,*.oxt} |*.zip;*.oxt.
        /// </summary>
        public static string FileDialogLoadOODictionaryFilter {
            get {
                return ResourceManager.GetString("FileDialogLoadOODictionaryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory mluvčích (*{0})|*{1}|Všechny soubory (*.*)|*.*.
        /// </summary>
        public static string FileDialogLoadSpeakersDatabaseFilter {
            get {
                return ResourceManager.GetString("FileDialogLoadSpeakersDatabaseFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít soubor s databází mluvčích....
        /// </summary>
        public static string FileDialogLoadSpeakersDatabaseTitle {
            get {
                return ResourceManager.GetString("FileDialogLoadSpeakersDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory titulků (*.trsx)|*.trsx)|Všechny soubory (*.*)|*.*.
        /// </summary>
        public static string FileDialogLoadTranscriptionFilter {
            get {
                return ResourceManager.GetString("FileDialogLoadTranscriptionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít soubor s titulky....
        /// </summary>
        public static string FileDialogLoadTranscriptionTitle {
            get {
                return ResourceManager.GetString("FileDialogLoadTranscriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit databází mluvčích....
        /// </summary>
        public static string FileDialogSaveSpeakersDatabaseTitle {
            get {
                return ResourceManager.GetString("FileDialogSaveSpeakersDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory titulků (*.trsx)|*.trsx|Všechny soubory (*.*)|*.*.
        /// </summary>
        public static string FileDialogSaveTranscriptionFilter {
            get {
                return ResourceManager.GetString("FileDialogSaveTranscriptionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit soubor s titulky....
        /// </summary>
        public static string FileDialogSaveTranscriptionTitle {
            get {
                return ResourceManager.GetString("FileDialogSaveTranscriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozlišovat malá a velká písmena.
        /// </summary>
        public static string FindDialogCaseSensitiveCheckbox {
            get {
                return ResourceManager.GetString("FindDialogCaseSensitiveCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najít další.
        /// </summary>
        public static string FindDialogNextButton {
            get {
                return ResourceManager.GetString("FindDialogNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledat v mluvčích.
        /// </summary>
        public static string FindDialogSearchInSpeakersCheckbox {
            get {
                return ResourceManager.GetString("FindDialogSearchInSpeakersCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najít:.
        /// </summary>
        public static string FindDialogSearchLable {
            get {
                return ResourceManager.GetString("FindDialogSearchLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledání.
        /// </summary>
        public static string FindDialogTitle {
            get {
                return ResourceManager.GetString("FindDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledat regulárním výrazem.
        /// </summary>
        public static string FindDialogUseRegexCheckbox {
            get {
                return ResourceManager.GetString("FindDialogUseRegexCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavřít.
        /// </summary>
        public static string HelpWindowCloseButtonText {
            get {
                return ResourceManager.GetString("HelpWindowCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápověda.
        /// </summary>
        public static string HelpWindowTitle {
            get {
                return ResourceManager.GetString("HelpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor s danou příponou je možné importovat více pluginy, vyberte ten správný.
        /// </summary>
        public static string ImportSelectImportPlugin {
            get {
                return ResourceManager.GetString("ImportSelectImportPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string infoPanelsVideoHeader {
            get {
                return ResourceManager.GetString("infoPanelsVideoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimediální soubory (*.wav, *.mp3, *.wma, *.avi, *.mpg, *.wmv)|*.wav;*.mp3;*.wma;*.avi;*.mpg;*.mpeg;*.wmv|Zvukové soubory (*.wav, *.mp3, *.wma)|*.wav;*.mp3;*.wma|Všechny soubory (*.*)|*.*.
        /// </summary>
        public static string LoadAudioFilter {
            get {
                return ResourceManager.GetString("LoadAudioFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít zvukový soubor....
        /// </summary>
        public static string LoadAudioTitle {
            get {
                return ResourceManager.GetString("LoadAudioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video soubor (*.avi, *.mpg, *.wmv)|*.avi;*.mpg;*.mpeg;*.wmv|Všechny soubory (*.*)|*.*.
        /// </summary>
        public static string LoadVideoFilter {
            get {
                return ResourceManager.GetString("LoadVideoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít video soubor....
        /// </summary>
        public static string LoadVideoTitle {
            get {
                return ResourceManager.GetString("LoadVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio:.
        /// </summary>
        public static string mainWindowAudioPanelHeader {
            get {
                return ResourceManager.GetString("mainWindowAudioPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio....
        /// </summary>
        public static string mainWindowLoadAudioButtonText {
            get {
                return ResourceManager.GetString("mainWindowLoadAudioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Převod audia:.
        /// </summary>
        public static string mainWindowStatusbarAudioConversionHeader {
            get {
                return ResourceManager.GetString("mainWindowStatusbarAudioConversionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Převod souboru dokončen!.
        /// </summary>
        public static string mainWindowStatusbarStatusTextConversionDone {
            get {
                return ResourceManager.GetString("mainWindowStatusbarStatusTextConversionDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probíhá převod vybraného audio souboru na podporovaný formát....
        /// </summary>
        public static string mainWindowStatusbarStatusTextConversionRunning {
            get {
                return ResourceManager.GetString("mainWindowStatusbarStatusTextConversionRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Připraven.
        /// </summary>
        public static string mainWindowStatusbarStatusTextReady {
            get {
                return ResourceManager.GetString("mainWindowStatusbarStatusTextReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úpravy.
        /// </summary>
        public static string menuEdit {
            get {
                return ResourceManager.GetString("menuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat položku.
        /// </summary>
        public static string menuEditDeleteElement {
            get {
                return ResourceManager.GetString("menuEditDeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstraň neřečové události.
        /// </summary>
        public static string menuEditDeleteNonSpeechEvents {
            get {
                return ResourceManager.GetString("menuEditDeleteNonSpeechEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová kapitola.
        /// </summary>
        public static string menuEditNewChapter {
            get {
                return ResourceManager.GetString("menuEditNewChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová sekce na pozici.
        /// </summary>
        public static string menuEditNewSection {
            get {
                return ResourceManager.GetString("menuEditNewSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor.
        /// </summary>
        public static string menuFile {
            get {
                return ResourceManager.GetString("menuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec.
        /// </summary>
        public static string menuFileExit {
            get {
                return ResourceManager.GetString("menuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportovat (Ctrl+Shift+E).
        /// </summary>
        public static string menufileExport {
            get {
                return ResourceManager.GetString("menufileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importovat (Ctrl+Shift+I).
        /// </summary>
        public static string menuFileImport {
            get {
                return ResourceManager.GetString("menuFileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový přepis.
        /// </summary>
        public static string menuFileNewTranscription {
            get {
                return ResourceManager.GetString("menuFileNewTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít audio.
        /// </summary>
        public static string menufileOpenAudio {
            get {
                return ResourceManager.GetString("menufileOpenAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít přepis.
        /// </summary>
        public static string menuFileOpenTranscription {
            get {
                return ResourceManager.GetString("menuFileOpenTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít video.
        /// </summary>
        public static string menuFileOpenVideo {
            get {
                return ResourceManager.GetString("menuFileOpenVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit přepis.
        /// </summary>
        public static string menuFileSave {
            get {
                return ResourceManager.GetString("menuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit přepis jako.
        /// </summary>
        public static string menuFileSaveAs {
            get {
                return ResourceManager.GetString("menuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápověda.
        /// </summary>
        public static string menuHelp {
            get {
                return ResourceManager.GetString("menuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programu.
        /// </summary>
        public static string menuHelpAbout {
            get {
                return ResourceManager.GetString("menuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis programu.
        /// </summary>
        public static string menuHelpHelp {
            get {
                return ResourceManager.GetString("menuHelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Nástroje.
        /// </summary>
        public static string menuTools {
            get {
                return ResourceManager.GetString("menuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonetický přepis.
        /// </summary>
        public static string menuToolsFonetics {
            get {
                return ResourceManager.GetString("menuToolsFonetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit fonetický přepis.
        /// </summary>
        public static string menuToolsFoneticsShow {
            get {
                return ResourceManager.GetString("menuToolsFoneticsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastav mluvčího.
        /// </summary>
        public static string menuToolsSetSpeaker {
            get {
                return ResourceManager.GetString("menuToolsSetSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        public static string menuToolsSettings {
            get {
                return ResourceManager.GetString("menuToolsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string menuToolsVideo {
            get {
                return ResourceManager.GetString("menuToolsVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit Video.
        /// </summary>
        public static string menuToolsVideoShow {
            get {
                return ResourceManager.GetString("menuToolsVideoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor, který se pokoušíte přehrát není podporován nebo je poškozený.
        /// </summary>
        public static string MessageBoxAudioFormatError {
            get {
                return ResourceManager.GetString("MessageBoxAudioFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze vytvořit obrázek mluvčího, protože není načteno video.
        /// </summary>
        public static string MessageBoxCannotTakeSnapshotVideoNotLoaded {
            get {
                return ResourceManager.GetString("MessageBoxCannotTakeSnapshotVideoNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba pri derializaci konfiguračního souboru souboru:.
        /// </summary>
        public static string MessageBoxConfigFileDeserializationError {
            get {
                return ResourceManager.GetString("MessageBoxConfigFileDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat vybraného mluvčího z databáze programu?.
        /// </summary>
        public static string MessageBoxConfirmSpeakerDeletion {
            get {
                return ResourceManager.GetString("MessageBoxConfirmSpeakerDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat vybraného mluvčího z příslušného seznamu i datové struktury, pokud je v ní přítomen?.
        /// </summary>
        public static string MessageBoxConfirmUsedSpeakerDeletion {
            get {
                return ResourceManager.GetString("MessageBoxConfirmUsedSpeakerDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovníky pro kontrolu pravopisu byly nainstalovány.
        /// </summary>
        public static string MessageBoxDictinaryInstalled {
            get {
                return ResourceManager.GetString("MessageBoxDictinaryInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst slovník {0}?.
        /// </summary>
        public static string MessageBoxDictionaryConfirmLoad {
            get {
                return ResourceManager.GetString("MessageBoxDictionaryConfirmLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor nebyl stažen, uživatel zastavil stahování, cílová adresa už neexistuje, nebo není dostupné připojení k internetu.
        /// </summary>
        public static string MessageBoxDictionaryDownloadError {
            get {
                return ResourceManager.GetString("MessageBoxDictionaryDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problém se stahováním z internetu.
        /// </summary>
        public static string MessageBoxDictionaryDownloadErrorCaption {
            get {
                return ResourceManager.GetString("MessageBoxDictionaryDownloadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor nelze otevřít, je poškozený, nebo to není rozšíření Open Office 3.
        /// </summary>
        public static string MessageBoxDictionaryFormatError {
            get {
                return ResourceManager.GetString("MessageBoxDictionaryFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string MessageBoxErrorCaption {
            get {
                return ResourceManager.GetString("MessageBoxErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export souboru skončil chybou.
        /// </summary>
        public static string MessageBoxExportError {
            get {
                return ResourceManager.GetString("MessageBoxExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import souboru skončil chybou.
        /// </summary>
        public static string MessageBoxImportError {
            get {
                return ResourceManager.GetString("MessageBoxImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informace.
        /// </summary>
        public static string MessageBoxInfoCaption {
            get {
                return ResourceManager.GetString("MessageBoxInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databáze mluvčích je nedostupná, změňte cestu v nastavení.
        /// </summary>
        public static string MessageBoxLocalSpeakersDatabaseUnreachableLoad {
            get {
                return ResourceManager.GetString("MessageBoxLocalSpeakersDatabaseUnreachableLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesta k databázi mluvčích je neplatná, mluvčí nebudou uloženi (v nastavní jde cesta změnit).
        /// </summary>
        public static string MessageBoxLocalSpeakersDatabaseUnreachableSave {
            get {
                return ResourceManager.GetString("MessageBoxLocalSpeakersDatabaseUnreachableSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba pri otevirani prepisu: .
        /// </summary>
        public static string MessageBoxOpenTranscriptionError {
            get {
                return ResourceManager.GetString("MessageBoxOpenTranscriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otázka:.
        /// </summary>
        public static string MessageBoxQuestionCaption {
            get {
                return ResourceManager.GetString("MessageBoxQuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přepis není uložený. Chcete ho nyní uložit?.
        /// </summary>
        public static string MessageBoxSaveBeforeClosing {
            get {
                return ResourceManager.GetString("MessageBoxSaveBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba pri ukladani titulku:.
        /// </summary>
        public static string MessageBoxSaveTranscriptionError {
            get {
                return ResourceManager.GetString("MessageBoxSaveTranscriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyhledávání.
        /// </summary>
        public static string MessageBoxSearchCaption {
            get {
                return ResourceManager.GetString("MessageBoxSearchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyhledávaný výraz nebyl nalezen, začít znovu od začátku dokumentu?.
        /// </summary>
        public static string MessageBoxSearchTryFromBegining {
            get {
                return ResourceManager.GetString("MessageBoxSearchTryFromBegining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze Převést.
        /// </summary>
        public static string MessageBoxSpeakerCannotReplace {
            get {
                return ResourceManager.GetString("MessageBoxSpeakerCannotReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Převedeno.
        /// </summary>
        public static string MessageBoxSpeakerReplaceDone {
            get {
                return ResourceManager.GetString("MessageBoxSpeakerReplaceDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není výbraný mluvčí na kterého neviditelné převést.
        /// </summary>
        public static string MessageBoxSpeakerReplaceTargetNotSelected {
            get {
                return ResourceManager.GetString("MessageBoxSpeakerReplaceTargetNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstavec nemůže být kratší než 100ms.
        /// </summary>
        public static string MessageBoxTooShortParagraph {
            get {
                return ResourceManager.GetString("MessageBoxTooShortParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete použít jako zdroj audia načítaný video soubor?.
        /// </summary>
        public static string MessageBoxUseVideoFileAsAudioSource {
            get {
                return ResourceManager.GetString("MessageBoxUseVideoFileAsAudioSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varování.
        /// </summary>
        public static string MessageBoxWarningCaption {
            get {
                return ResourceManager.GetString("MessageBoxWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro instalaci slovníků si musíte být vědomi tohoto:.
        /// </summary>
        public static string OODictionaryLicenceTitle {
            get {
                return ResourceManager.GetString("OODictionaryLicenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr.
        /// </summary>
        public static string PickOneDialogFilterLabel {
            get {
                return ResourceManager.GetString("PickOneDialogFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string PickOneDialogOKButton {
            get {
                return ResourceManager.GetString("PickOneDialogOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žena.
        /// </summary>
        public static string SexConversionFemale {
            get {
                return ResourceManager.GetString("SexConversionFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muž.
        /// </summary>
        public static string SexConversionMale {
            get {
                return ResourceManager.GetString("SexConversionMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TextWallWindowCancelButton {
            get {
                return ResourceManager.GetString("TextWallWindowCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string TextWallWindowOKButton {
            get {
                return ResourceManager.GetString("TextWallWindowOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextWallWindow.
        /// </summary>
        public static string TextWallWindowTitle {
            get {
                return ResourceManager.GetString("TextWallWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posunout zbytek +50ms.
        /// </summary>
        public static string TranscriptionContextMenuAdd50ms {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuAdd50ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat....
        /// </summary>
        public static string TranscriptionContextMenuDeleteElement {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuDeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportovat záznam.
        /// </summary>
        public static string TranscriptionContextMenuExport {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová kapitola.
        /// </summary>
        public static string TranscriptionContextMenuNewChapter {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuNewChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová sekce.
        /// </summary>
        public static string TranscriptionContextMenuNewSection {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuNewSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová sekce na pozici.
        /// </summary>
        public static string TranscriptionContextMenuNewSectionAtPosition {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuNewSectionAtPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastav mluvčího.
        /// </summary>
        public static string TranscriptionContextMenuSetSpeaker {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuSetSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posunout zbytek -50ms.
        /// </summary>
        public static string TranscriptionContextMenuSubstract50ms {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuSubstract50ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sejmout obrázek mlvčího.
        /// </summary>
        public static string VideoContextMenuTakeSnapshot {
            get {
                return ResourceManager.GetString("VideoContextMenuTakeSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přiřadit čas konce elementu.
        /// </summary>
        public static string WaveformContextMenuSetEnd {
            get {
                return ResourceManager.GetString("WaveformContextMenuSetEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přiřadit čas výběru elementu.
        /// </summary>
        public static string WaveformContextMenuSetSelection {
            get {
                return ResourceManager.GetString("WaveformContextMenuSetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přiřadit čas začátku elementu.
        /// </summary>
        public static string WaveformContextMenuSetStart {
            get {
                return ResourceManager.GetString("WaveformContextMenuSetStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posunout přepis - začátek ke kurzoru.
        /// </summary>
        public static string WaveformContextMenuSetStartToCursor {
            get {
                return ResourceManager.GetString("WaveformContextMenuSetStartToCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehrávání zvuku.
        /// </summary>
        public static string WinSetupAudioPlayback {
            get {
                return ResourceManager.GetString("WinSetupAudioPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záznam zvuku.
        /// </summary>
        public static string WinSetupAudioRecording {
            get {
                return ResourceManager.GetString("WinSetupAudioRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Audio.
        /// </summary>
        public static string WinSetupAudioTab {
            get {
                return ResourceManager.GetString("WinSetupAudioTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vstupní zažízení:.
        /// </summary>
        public static string WinSetupInputDevices {
            get {
                return ResourceManager.GetString("WinSetupInputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délka skoku:.
        /// </summary>
        public static string WinSetupJumpLength {
            get {
                return ResourceManager.GetString("WinSetupJumpLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string WinSetupOKButton {
            get {
                return ResourceManager.GetString("WinSetupOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatní.
        /// </summary>
        public static string WinSetupOthersTab {
            get {
                return ResourceManager.GetString("WinSetupOthersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výstupní zažízení:.
        /// </summary>
        public static string WinSetupOutputDevices {
            get {
                return ResourceManager.GetString("WinSetupOutputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení Přehrávání.
        /// </summary>
        public static string WinSetupPlaybackSettings {
            get {
                return ResourceManager.GetString("WinSetupPlaybackSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehrávání.
        /// </summary>
        public static string WinSetupPlaybackTab {
            get {
                return ResourceManager.GetString("WinSetupPlaybackTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpomalené přehrávání - rychlost:.
        /// </summary>
        public static string WinSetupSlowPlaybackSpeed {
            get {
                return ResourceManager.GetString("WinSetupSlowPlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst....
        /// </summary>
        public static string WinSetupSpeakersDatabaseButtonTitle {
            get {
                return ResourceManager.GetString("WinSetupSpeakersDatabaseButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor:.
        /// </summary>
        public static string WinSetupSpeakersDatabaseLabelTitle {
            get {
                return ResourceManager.GetString("WinSetupSpeakersDatabaseLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výchozí databáze mluvčích.
        /// </summary>
        public static string WinSetupSpeakersDatabaseTitle {
            get {
                return ResourceManager.GetString("WinSetupSpeakersDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stáhnout slovník automaticky.
        /// </summary>
        public static string WinSetupSpellchekingDownloadAutomatically {
            get {
                return ResourceManager.GetString("WinSetupSpellchekingDownloadAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst slovníky ručně.
        /// </summary>
        public static string WinSetupSpellchekingSetManually {
            get {
                return ResourceManager.GetString("WinSetupSpellchekingSetManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellcheking Slovníky.
        /// </summary>
        public static string WinSetupSpellchekingTitle {
            get {
                return ResourceManager.GetString("WinSetupSpellchekingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizovat slovník automaticky.
        /// </summary>
        public static string WinSetupSpellchekingUpdateAutomatically {
            get {
                return ResourceManager.GetString("WinSetupSpellchekingUpdateAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno.
        /// </summary>
        public static string WinSetupStornoButton {
            get {
                return ResourceManager.GetString("WinSetupStornoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velikost textu přepisu:.
        /// </summary>
        public static string WinSetupTextualTranscriptionFontSize {
            get {
                return ResourceManager.GetString("WinSetupTextualTranscriptionFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velikost:.
        /// </summary>
        public static string WinSetupTextualTranscriptionImageSize {
            get {
                return ResourceManager.GetString("WinSetupTextualTranscriptionImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit fotografii mluvčího.
        /// </summary>
        public static string WinSetupTextualTranscriptionShowImage {
            get {
                return ResourceManager.GetString("WinSetupTextualTranscriptionShowImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textový přepis.
        /// </summary>
        public static string WinSetupTextualTranscriptionTitle {
            get {
                return ResourceManager.GetString("WinSetupTextualTranscriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        public static string WinSetupTitle {
            get {
                return ResourceManager.GetString("WinSetupTitle", resourceCulture);
            }
        }
    }
}
