//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoTrans.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanoTrans.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph language.
        /// </summary>
        public static string ContextMenuLanguageHeader {
            get {
                return ResourceManager.GetString("ContextMenuLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 0.
        /// </summary>
        public static string DefaultChapterText {
            get {
                return ResourceManager.GetString("DefaultChapterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 0.
        /// </summary>
        public static string DefaultSectionText {
            get {
                return ResourceManager.GetString("DefaultSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string DownloadFileWindowTitle {
            get {
                return ResourceManager.GetString("DownloadFileWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occured. To prevent the corruption, please save transcription to new file  and restart the NanoTrans..
        /// </summary>
        public static string ExceptionWindowBigMessage {
            get {
                return ResourceManager.GetString("ExceptionWindowBigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception detail:.
        /// </summary>
        public static string ExceptionWindowExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionWindowExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and restart.
        /// </summary>
        public static string ExceptionWindowSaveAndRestartButton {
            get {
                return ResourceManager.GetString("ExceptionWindowSaveAndRestartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured.
        /// </summary>
        public static string ExceptionWindowTitle {
            get {
                return ResourceManager.GetString("ExceptionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg;*.jpeg;*.png;*.gif;*.bmp|All files (*.*)|*.*.
        /// </summary>
        public static string FileDialogLoadImageFilter {
            get {
                return ResourceManager.GetString("FileDialogLoadImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file with a speaker miniature.
        /// </summary>
        public static string FileDialogLoadImageTitle {
            get {
                return ResourceManager.GetString("FileDialogLoadImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All importable files({0})|{0}.
        /// </summary>
        public static string FileDialogLoadImportFilter {
            get {
                return ResourceManager.GetString("FileDialogLoadImportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file.
        /// </summary>
        public static string FileDialogLoadImportTitle {
            get {
                return ResourceManager.GetString("FileDialogLoadImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenOffice 3 plugins {*.zip,*.oxt} |*.zip;*.oxt.
        /// </summary>
        public static string FileDialogLoadOODictionaryFilter {
            get {
                return ResourceManager.GetString("FileDialogLoadOODictionaryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker database file (*{0})|*{1}|All Files (*.*)|*.*.
        /// </summary>
        public static string FileDialogLoadSpeakersDatabaseFilter {
            get {
                return ResourceManager.GetString("FileDialogLoadSpeakersDatabaseFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open speakers database.
        /// </summary>
        public static string FileDialogLoadSpeakersDatabaseTitle {
            get {
                return ResourceManager.GetString("FileDialogLoadSpeakersDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription Files (*.trsx)|*.trsx|All Files (*.*)|*.*.
        /// </summary>
        public static string FileDialogLoadTranscriptionFilter {
            get {
                return ResourceManager.GetString("FileDialogLoadTranscriptionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open transcription file ....
        /// </summary>
        public static string FileDialogLoadTranscriptionTitle {
            get {
                return ResourceManager.GetString("FileDialogLoadTranscriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Speakers database ...
        /// </summary>
        public static string FileDialogSaveSpeakersDatabaseTitle {
            get {
                return ResourceManager.GetString("FileDialogSaveSpeakersDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription Files (*.trsx)|*.trsx|All files (*.*)|*.*.
        /// </summary>
        public static string FileDialogSaveTranscriptionFilter {
            get {
                return ResourceManager.GetString("FileDialogSaveTranscriptionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save transcription file....
        /// </summary>
        public static string FileDialogSaveTranscriptionTitle {
            get {
                return ResourceManager.GetString("FileDialogSaveTranscriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case senitive search.
        /// </summary>
        public static string FindDialogCaseSensitiveCheckbox {
            get {
                return ResourceManager.GetString("FindDialogCaseSensitiveCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next.
        /// </summary>
        public static string FindDialogNextButton {
            get {
                return ResourceManager.GetString("FindDialogNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Speakers.
        /// </summary>
        public static string FindDialogSearchInSpeakersCheckbox {
            get {
                return ResourceManager.GetString("FindDialogSearchInSpeakersCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        public static string FindDialogSearchLable {
            get {
                return ResourceManager.GetString("FindDialogSearchLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindDialogTitle {
            get {
                return ResourceManager.GetString("FindDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regular expressions.
        /// </summary>
        public static string FindDialogUseRegexCheckbox {
            get {
                return ResourceManager.GetString("FindDialogUseRegexCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment,Marital status,Nationality,Employment.
        /// </summary>
        public static string GlobalDefaultSpeakerAttributes {
            get {
                return ResourceManager.GetString("GlobalDefaultSpeakerAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cough,ehm,laugh,silence,breath,noise,music,smack.
        /// </summary>
        public static string GlobalNonSpeechEvents {
            get {
                return ResourceManager.GetString("GlobalNonSpeechEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string HelpWindowCloseButtonText {
            get {
                return ResourceManager.GetString("HelpWindowCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpWindowTitle {
            get {
                return ResourceManager.GetString("HelpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File can be imported by two or more plugins, please select one. .
        /// </summary>
        public static string ImportSelectImportPlugin {
            get {
                return ResourceManager.GetString("ImportSelectImportPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string infoPanelsVideoHeader {
            get {
                return ResourceManager.GetString("infoPanelsVideoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia files (*.wav, *.mp3, *.wma, *.avi, *.mpg, *.wmv)|*.wav;*.mp3;*.wma;*.avi;*.mpg;*.mpeg;*.wmv|Audio files(*.wav, *.mp3, *.wma)|*.wav;*.mp3;*.wma|All files (*.*)|*.*.
        /// </summary>
        public static string LoadAudioFilter {
            get {
                return ResourceManager.GetString("LoadAudioFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open audio file....
        /// </summary>
        public static string LoadAudioTitle {
            get {
                return ResourceManager.GetString("LoadAudioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video file (*.avi, *.mpg, *.wmv)|*.avi;*.mpg;*.mpeg;*.wmv|Všechny soubory (*.*)|*.*.
        /// </summary>
        public static string LoadVideoFilter {
            get {
                return ResourceManager.GetString("LoadVideoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open video file....
        /// </summary>
        public static string LoadVideoTitle {
            get {
                return ResourceManager.GetString("LoadVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio:.
        /// </summary>
        public static string mainWindowAudioPanelHeader {
            get {
                return ResourceManager.GetString("mainWindowAudioPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Non-Speech events.
        /// </summary>
        public static string mainWindowHideNonSpeechEventsTooltip {
            get {
                return ResourceManager.GetString("mainWindowHideNonSpeechEventsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio....
        /// </summary>
        public static string mainWindowLoadAudioButtonText {
            get {
                return ResourceManager.GetString("mainWindowLoadAudioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker synchronization.
        /// </summary>
        public static string mainWindowOpenSpeakerSynchronizerTooltip {
            get {
                return ResourceManager.GetString("mainWindowOpenSpeakerSynchronizerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio conversion:.
        /// </summary>
        public static string mainWindowStatusbarAudioConversionHeader {
            get {
                return ResourceManager.GetString("mainWindowStatusbarAudioConversionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio loading progress.
        /// </summary>
        public static string mainWindowStatusbarAudioConversionTooltip {
            get {
                return ResourceManager.GetString("mainWindowStatusbarAudioConversionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion done!.
        /// </summary>
        public static string mainWindowStatusbarStatusTextConversionDone {
            get {
                return ResourceManager.GetString("mainWindowStatusbarStatusTextConversionDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting audio....
        /// </summary>
        public static string mainWindowStatusbarStatusTextConversionRunning {
            get {
                return ResourceManager.GetString("mainWindowStatusbarStatusTextConversionRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string mainWindowStatusbarStatusTextReady {
            get {
                return ResourceManager.GetString("mainWindowStatusbarStatusTextReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale waveform height automatically.
        /// </summary>
        public static string mainWindowWaveformHeightAuto {
            get {
                return ResourceManager.GetString("mainWindowWaveformHeightAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale waveform height in.
        /// </summary>
        public static string mainWindowWaveformHeightIn {
            get {
                return ResourceManager.GetString("mainWindowWaveformHeightIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale waveform height out.
        /// </summary>
        public static string mainWindowWaveformHeightOut {
            get {
                return ResourceManager.GetString("mainWindowWaveformHeightOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowed Playback.
        /// </summary>
        public static string mainWindowWaveformSlowPlayback {
            get {
                return ResourceManager.GetString("mainWindowWaveformSlowPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string menuEdit {
            get {
                return ResourceManager.GetString("menuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete element.
        /// </summary>
        public static string menuEditDeleteElement {
            get {
                return ResourceManager.GetString("menuEditDeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove non-speech events.
        /// </summary>
        public static string menuEditDeleteNonSpeechEvents {
            get {
                return ResourceManager.GetString("menuEditDeleteNonSpeechEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New chapter.
        /// </summary>
        public static string menuEditNewChapter {
            get {
                return ResourceManager.GetString("menuEditNewChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New section at selected position.
        /// </summary>
        public static string menuEditNewSection {
            get {
                return ResourceManager.GetString("menuEditNewSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string menuFile {
            get {
                return ResourceManager.GetString("menuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string menuFileExit {
            get {
                return ResourceManager.GetString("menuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export (Ctrl+Shift+E).
        /// </summary>
        public static string menufileExport {
            get {
                return ResourceManager.GetString("menufileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import (Ctrl+Shift+I).
        /// </summary>
        public static string menuFileImport {
            get {
                return ResourceManager.GetString("menuFileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New transcription.
        /// </summary>
        public static string menuFileNewTranscription {
            get {
                return ResourceManager.GetString("menuFileNewTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open audio.
        /// </summary>
        public static string menufileOpenAudio {
            get {
                return ResourceManager.GetString("menufileOpenAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open transcription.
        /// </summary>
        public static string menuFileOpenTranscription {
            get {
                return ResourceManager.GetString("menuFileOpenTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open video.
        /// </summary>
        public static string menuFileOpenVideo {
            get {
                return ResourceManager.GetString("menuFileOpenVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save transcription.
        /// </summary>
        public static string menuFileSave {
            get {
                return ResourceManager.GetString("menuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save transcription as.
        /// </summary>
        public static string menuFileSaveAs {
            get {
                return ResourceManager.GetString("menuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string menuHelp {
            get {
                return ResourceManager.GetString("menuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string menuHelpAbout {
            get {
                return ResourceManager.GetString("menuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string menuHelpHelp {
            get {
                return ResourceManager.GetString("menuHelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string menuTools {
            get {
                return ResourceManager.GetString("menuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonetic Transcription.
        /// </summary>
        public static string menuToolsFonetics {
            get {
                return ResourceManager.GetString("menuToolsFonetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show fonetic transcription.
        /// </summary>
        public static string menuToolsFoneticsShow {
            get {
                return ResourceManager.GetString("menuToolsFoneticsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set speaker.
        /// </summary>
        public static string menuToolsSetSpeaker {
            get {
                return ResourceManager.GetString("menuToolsSetSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string menuToolsSettings {
            get {
                return ResourceManager.GetString("menuToolsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string menuToolsVideo {
            get {
                return ResourceManager.GetString("menuToolsVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Show Video.
        /// </summary>
        public static string menuToolsVideoShow {
            get {
                return ResourceManager.GetString("menuToolsVideoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file format cannot be opened. The file is corrupted or  in an invalid format..
        /// </summary>
        public static string MessageBoxAudioFormatError {
            get {
                return ResourceManager.GetString("MessageBoxAudioFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot capture a speaker miniature, video is not loaded-.
        /// </summary>
        public static string MessageBoxCannotTakeSnapshotVideoNotLoaded {
            get {
                return ResourceManager.GetString("MessageBoxCannotTakeSnapshotVideoNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when loading program settings.
        /// </summary>
        public static string MessageBoxConfigFileDeserializationError {
            get {
                return ResourceManager.GetString("MessageBoxConfigFileDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want to delete selected speaker from database?.
        /// </summary>
        public static string MessageBoxConfirmSpeakerDeletion {
            get {
                return ResourceManager.GetString("MessageBoxConfirmSpeakerDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want to delete selected speaker from database? (speaker is used in current transcription and will be replaced by the empty speaker).
        /// </summary>
        public static string MessageBoxConfirmUsedSpeakerDeletion {
            get {
                return ResourceManager.GetString("MessageBoxConfirmUsedSpeakerDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellchecking dictionary was installed.
        /// </summary>
        public static string MessageBoxDictinaryInstalled {
            get {
                return ResourceManager.GetString("MessageBoxDictinaryInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load spellcheking dictionary {0}?.
        /// </summary>
        public static string MessageBoxDictionaryConfirmLoad {
            get {
                return ResourceManager.GetString("MessageBoxDictionaryConfirmLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download file, download was canceled by the user, file was removed from server or the internet connection is not active..
        /// </summary>
        public static string MessageBoxDictionaryDownloadError {
            get {
                return ResourceManager.GetString("MessageBoxDictionaryDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading error.
        /// </summary>
        public static string MessageBoxDictionaryDownloadErrorCaption {
            get {
                return ResourceManager.GetString("MessageBoxDictionaryDownloadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the file. file is corrupted or not in the Open Office 3 format.
        /// </summary>
        public static string MessageBoxDictionaryFormatError {
            get {
                return ResourceManager.GetString("MessageBoxDictionaryFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxErrorCaption {
            get {
                return ResourceManager.GetString("MessageBoxErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during export....
        /// </summary>
        public static string MessageBoxExportError {
            get {
                return ResourceManager.GetString("MessageBoxExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during import....
        /// </summary>
        public static string MessageBoxImportError {
            get {
                return ResourceManager.GetString("MessageBoxImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MessageBoxInfoCaption {
            get {
                return ResourceManager.GetString("MessageBoxInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Speakers Database file is unreachable, please set valid location in settings..
        /// </summary>
        public static string MessageBoxLocalSpeakersDatabaseUnreachableLoad {
            get {
                return ResourceManager.GetString("MessageBoxLocalSpeakersDatabaseUnreachableLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Speakers Database file is unreachablecannot save speakers..
        /// </summary>
        public static string MessageBoxLocalSpeakersDatabaseUnreachableSave {
            get {
                return ResourceManager.GetString("MessageBoxLocalSpeakersDatabaseUnreachableSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured in the transcription: .
        /// </summary>
        public static string MessageBoxOpenTranscriptionError {
            get {
                return ResourceManager.GetString("MessageBoxOpenTranscriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question:.
        /// </summary>
        public static string MessageBoxQuestionCaption {
            get {
                return ResourceManager.GetString("MessageBoxQuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current transcription is not saved. Save now?.
        /// </summary>
        public static string MessageBoxSaveBeforeClosing {
            get {
                return ResourceManager.GetString("MessageBoxSaveBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save transcription (exception occured).
        /// </summary>
        public static string MessageBoxSaveTranscriptionError {
            get {
                return ResourceManager.GetString("MessageBoxSaveTranscriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string MessageBoxSearchCaption {
            get {
                return ResourceManager.GetString("MessageBoxSearchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified text was not found, start again from the start?.
        /// </summary>
        public static string MessageBoxSearchTryFromBegining {
            get {
                return ResourceManager.GetString("MessageBoxSearchTryFromBegining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert.
        /// </summary>
        public static string MessageBoxSpeakerCannotReplace {
            get {
                return ResourceManager.GetString("MessageBoxSpeakerCannotReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to converted.
        /// </summary>
        public static string MessageBoxSpeakerReplaceDone {
            get {
                return ResourceManager.GetString("MessageBoxSpeakerReplaceDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target speaker is not selected..
        /// </summary>
        public static string MessageBoxSpeakerReplaceTargetNotSelected {
            get {
                return ResourceManager.GetString("MessageBoxSpeakerReplaceTargetNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any paragraph cannot be shorter than 100ms.
        /// </summary>
        public static string MessageBoxTooShortParagraph {
            get {
                return ResourceManager.GetString("MessageBoxTooShortParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the video file as  an audio source?.
        /// </summary>
        public static string MessageBoxUseVideoFileAsAudioSource {
            get {
                return ResourceManager.GetString("MessageBoxUseVideoFileAsAudioSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBoxWarningCaption {
            get {
                return ResourceManager.GetString("MessageBoxWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to accept the licence agreement of spellchecking dictionary.
        /// </summary>
        public static string OODictionaryLicenceTitle {
            get {
                return ResourceManager.GetString("OODictionaryLicenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string PickOneDialogFilterLabel {
            get {
                return ResourceManager.GetString("PickOneDialogFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string PickOneDialogOKButton {
            get {
                return ResourceManager.GetString("PickOneDialogOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string SexConversionFemale {
            get {
                return ResourceManager.GetString("SexConversionFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string SexConversionMale {
            get {
                return ResourceManager.GetString("SexConversionMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attribute.
        /// </summary>
        public static string SpeakerDetailsButtonAddAttribute {
            get {
                return ResourceManager.GetString("SpeakerDetailsButtonAddAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Attribure.
        /// </summary>
        public static string SpeakerDetailsButtonDeleteAttribute {
            get {
                return ResourceManager.GetString("SpeakerDetailsButtonDeleteAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit attribute.
        /// </summary>
        public static string SpeakerDetailsButtonEditAttribute {
            get {
                return ResourceManager.GetString("SpeakerDetailsButtonEditAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree after  za:.
        /// </summary>
        public static string SpeakerDetailsDegreeAfter {
            get {
                return ResourceManager.GetString("SpeakerDetailsDegreeAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degreee before:.
        /// </summary>
        public static string SpeakerDetailsDegreeBefore {
            get {
                return ResourceManager.GetString("SpeakerDetailsDegreeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string SpeakerDetailsFirstName {
            get {
                return ResourceManager.GetString("SpeakerDetailsFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker Attributes.
        /// </summary>
        public static string SpeakerDetailsLabelAttributes {
            get {
                return ResourceManager.GetString("SpeakerDetailsLabelAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name:.
        /// </summary>
        public static string SpeakerDetailsMiddleName {
            get {
                return ResourceManager.GetString("SpeakerDetailsMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string SpeakerDetailsOnlineReload {
            get {
                return ResourceManager.GetString("SpeakerDetailsOnlineReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SpeakerDetailsOnlineSave {
            get {
                return ResourceManager.GetString("SpeakerDetailsOnlineSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to document:.
        /// </summary>
        public static string SpeakerDetailsPinToCocument {
            get {
                return ResourceManager.GetString("SpeakerDetailsPinToCocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string SpeakerDetailsSurName {
            get {
                return ResourceManager.GetString("SpeakerDetailsSurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SpeakersManagerButtonCancel {
            get {
                return ResourceManager.GetString("SpeakersManagerButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New speaker.
        /// </summary>
        public static string SpeakersManagerButtonNewSpeaker {
            get {
                return ResourceManager.GetString("SpeakersManagerButtonNewSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string SpeakersManagerButtonOK {
            get {
                return ResourceManager.GetString("SpeakersManagerButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers from document.
        /// </summary>
        public static string SpeakersManagerCheckboxDocumentSpeakers {
            get {
                return ResourceManager.GetString("SpeakersManagerCheckboxDocumentSpeakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers from local database.
        /// </summary>
        public static string SpeakersManagerCheckboxLocalSpeakers {
            get {
                return ResourceManager.GetString("SpeakersManagerCheckboxLocalSpeakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers online.
        /// </summary>
        public static string SpeakersManagerCheckboxOnlineSpeakers {
            get {
                return ResourceManager.GetString("SpeakersManagerCheckboxOnlineSpeakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show speaker meniatures.
        /// </summary>
        public static string SpeakersManagerCheckboxShowMiniatures {
            get {
                return ResourceManager.GetString("SpeakersManagerCheckboxShowMiniatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SpeakersManagerContextMenuDelete {
            get {
                return ResourceManager.GetString("SpeakersManagerContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge with the other speakers.
        /// </summary>
        public static string SpeakersManagerContextMenuMerge {
            get {
                return ResourceManager.GetString("SpeakersManagerContextMenuMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sepaker.
        /// </summary>
        public static string SpeakersManagerContextMenuNew {
            get {
                return ResourceManager.GetString("SpeakersManagerContextMenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace int transcription with.
        /// </summary>
        public static string SpeakersManagerContextMenuReplace {
            get {
                return ResourceManager.GetString("SpeakersManagerContextMenuReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        public static string SpeakersManagerLabelSearch {
            get {
                return ResourceManager.GetString("SpeakersManagerLabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers manager.
        /// </summary>
        public static string SpeakersManagerTitle {
            get {
                return ResourceManager.GetString("SpeakersManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string SpeakersSynchronizerButtonOK {
            get {
                return ResourceManager.GetString("SpeakersSynchronizerButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Link.
        /// </summary>
        public static string SpeakersSynchronizerContextMenuRemoveLink {
            get {
                return ResourceManager.GetString("SpeakersSynchronizerContextMenuRemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers from document:.
        /// </summary>
        public static string SpeakersSynchronizerLabelDocumentList {
            get {
                return ResourceManager.GetString("SpeakersSynchronizerLabelDocumentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers from local database:.
        /// </summary>
        public static string SpeakersSynchronizerLabelLocalList {
            get {
                return ResourceManager.GetString("SpeakersSynchronizerLabelLocalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization of the speakers.
        /// </summary>
        public static string SpeakersSynchronizerTitle {
            get {
                return ResourceManager.GetString("SpeakersSynchronizerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TextWallWindowCancelButton {
            get {
                return ResourceManager.GetString("TextWallWindowCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string TextWallWindowOKButton {
            get {
                return ResourceManager.GetString("TextWallWindowOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextWallWindow.
        /// </summary>
        public static string TextWallWindowTitle {
            get {
                return ResourceManager.GetString("TextWallWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move remaining +50ms.
        /// </summary>
        public static string TranscriptionContextMenuAdd50ms {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuAdd50ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete....
        /// </summary>
        public static string TranscriptionContextMenuDeleteElement {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuDeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export paragraph.
        /// </summary>
        public static string TranscriptionContextMenuExport {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New chapter.
        /// </summary>
        public static string TranscriptionContextMenuNewChapter {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuNewChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New section.
        /// </summary>
        public static string TranscriptionContextMenuNewSection {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuNewSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New section at position.
        /// </summary>
        public static string TranscriptionContextMenuNewSectionAtPosition {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuNewSectionAtPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set speaker.
        /// </summary>
        public static string TranscriptionContextMenuSetSpeaker {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuSetSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move remaining -50ms.
        /// </summary>
        public static string TranscriptionContextMenuSubstract50ms {
            get {
                return ResourceManager.GetString("TranscriptionContextMenuSubstract50ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take image of the speaker.
        /// </summary>
        public static string VideoContextMenuTakeSnapshot {
            get {
                return ResourceManager.GetString("VideoContextMenuTakeSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the time to the end of the element.
        /// </summary>
        public static string WaveformContextMenuSetEnd {
            get {
                return ResourceManager.GetString("WaveformContextMenuSetEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the slecetion time to the element.
        /// </summary>
        public static string WaveformContextMenuSetSelection {
            get {
                return ResourceManager.GetString("WaveformContextMenuSetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the time to the begining of the element.
        /// </summary>
        public static string WaveformContextMenuSetStart {
            get {
                return ResourceManager.GetString("WaveformContextMenuSetStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move transcription - Start to the cursor.
        /// </summary>
        public static string WaveformContextMenuSetStartToCursor {
            get {
                return ResourceManager.GetString("WaveformContextMenuSetStartToCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Playback.
        /// </summary>
        public static string WinSetupAudioPlayback {
            get {
                return ResourceManager.GetString("WinSetupAudioPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Recording.
        /// </summary>
        public static string WinSetupAudioRecording {
            get {
                return ResourceManager.GetString("WinSetupAudioRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Audio.
        /// </summary>
        public static string WinSetupAudioTab {
            get {
                return ResourceManager.GetString("WinSetupAudioTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input devices:.
        /// </summary>
        public static string WinSetupInputDevices {
            get {
                return ResourceManager.GetString("WinSetupInputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump length:.
        /// </summary>
        public static string WinSetupJumpLength {
            get {
                return ResourceManager.GetString("WinSetupJumpLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        public static string WinSetupLocalizationTitle {
            get {
                return ResourceManager.GetString("WinSetupLocalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string WinSetupOKButton {
            get {
                return ResourceManager.GetString("WinSetupOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other settings.
        /// </summary>
        public static string WinSetupOthersTab {
            get {
                return ResourceManager.GetString("WinSetupOthersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output devices:.
        /// </summary>
        public static string WinSetupOutputDevices {
            get {
                return ResourceManager.GetString("WinSetupOutputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback settings.
        /// </summary>
        public static string WinSetupPlaybackSettings {
            get {
                return ResourceManager.GetString("WinSetupPlaybackSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string WinSetupPlaybackTab {
            get {
                return ResourceManager.GetString("WinSetupPlaybackTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowed plaback - speed:.
        /// </summary>
        public static string WinSetupSlowPlaybackSpeed {
            get {
                return ResourceManager.GetString("WinSetupSlowPlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load....
        /// </summary>
        public static string WinSetupSpeakersDatabaseButtonTitle {
            get {
                return ResourceManager.GetString("WinSetupSpeakersDatabaseButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string WinSetupSpeakersDatabaseLabelTitle {
            get {
                return ResourceManager.GetString("WinSetupSpeakersDatabaseLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers database loacation.
        /// </summary>
        public static string WinSetupSpeakersDatabaseTitle {
            get {
                return ResourceManager.GetString("WinSetupSpeakersDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download dictionary automaticaly.
        /// </summary>
        public static string WinSetupSpellchekingDownloadAutomatically {
            get {
                return ResourceManager.GetString("WinSetupSpellchekingDownloadAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file manually.
        /// </summary>
        public static string WinSetupSpellchekingSetManually {
            get {
                return ResourceManager.GetString("WinSetupSpellchekingSetManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellcheking dictionary.
        /// </summary>
        public static string WinSetupSpellchekingTitle {
            get {
                return ResourceManager.GetString("WinSetupSpellchekingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update dictionary automatically.
        /// </summary>
        public static string WinSetupSpellchekingUpdateAutomatically {
            get {
                return ResourceManager.GetString("WinSetupSpellchekingUpdateAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno.
        /// </summary>
        public static string WinSetupStornoButton {
            get {
                return ResourceManager.GetString("WinSetupStornoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription font size:.
        /// </summary>
        public static string WinSetupTextualTranscriptionFontSize {
            get {
                return ResourceManager.GetString("WinSetupTextualTranscriptionFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string WinSetupTextualTranscriptionImageSize {
            get {
                return ResourceManager.GetString("WinSetupTextualTranscriptionImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show speaker miniature.
        /// </summary>
        public static string WinSetupTextualTranscriptionShowImage {
            get {
                return ResourceManager.GetString("WinSetupTextualTranscriptionShowImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ortographic transcription.
        /// </summary>
        public static string WinSetupTextualTranscriptionTitle {
            get {
                return ResourceManager.GetString("WinSetupTextualTranscriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string WinSetupTitle {
            get {
                return ResourceManager.GetString("WinSetupTitle", resourceCulture);
            }
        }
    }
}
